# Generated by Django 3.2 on 2023-07-19 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20230719_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='ingredient',
        ),
    ]
